version: '3'

services:

    app:
      build:
        context: ./golang
      container_name: app_import_fiplan
      ports:
        - "9001:9000"
      volumes:
        - ./src:/go/src/
      networks:
        - netImportFiplan

    db:
      build:
        context: ./PostgreSQL
      container_name: pg_import_fiplan
      restart: always
      ports:
        - 54321:5432
      volumes:
      - ./PostgreSQL/data:/var/lib/postgresql/data       
      environment:
        POSTGRES_PASSWORD: 1234
      networks:
        - netImportFiplan

networks: 
  netImportFiplan:
    driver: bridge